### ISSUE TITLE
[AddOn] Helm values are not merged

### ISSUE THREAD

**Issue by allamand** [aws-quickstart/cdk-eks-blueprints#217]
When deploying an Helm Chart Addon, I would like to be able to configure it with the use of additional values parameters.

The AddOn constructs offer me to to this with a values filed, but It seams that the default values are not merged with the one I specify and that only the specified values are taken into account.

This can be difficult for applications where we could have hundreds of goo default parameters, we should be able to merge our values with default ones.

example:

```
                new ssp.ArgoCDAddOn( {
                    bootstrapRepo: {
                        repoUrl: gitUrl,
                        targetRevision: "main",
                        path: 'envs/dev'
                    },
                    adminPasswordSecretName: MultiRegionConstruct.SECRET_ARGO_ADMIN_PWD,
                    namespace: "argocd",
                    values: {
                            ingress: {
                                enabled: true,
                                hosts: [
                                 "argo."+subdomain,
                                ]
                            }
                        }
                    }
                }),
```

**Comment by danilko** [comment]
If understanding the problem correctly (others please feel free to correct/address):

Problems
---

The ArgoCD community has a default non-empty helm chart (and customer may have their own best practice) to deploy 
The current SSP utilize the AWS CDK's default HelmChart module to pass the value. The behavior is if values are present, it will use the values pass in to overwrite the entire helm chart 

I am thinking is is to solve merging of two helm value files (default vs one created by above parameter passed in)

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/helm-chart.ts , it is not doing any merge, but directly pass the value as is to custom resource
```
        Values: (props.values ? stack.toJsonString(props.values) : undefined),
```

The reason may due to helm v3 by itself does not support merge (still in discuss, but not exist yet) as discussed in this thread (the biggest concern is accidently bad results from merging)
https://github.com/helm/helm/issues/3486

So AWS CDK EKS Helm implementation seem to follow that idea and not performing merging on its own to create a "different behavior" than default helm chart behavior

SSP CDK follows that paractice, and some values are able to pick up as these are "known" to control and can just be override not merge

Few ideas to "bridge" these problems for now (assume Helm will not implement it nor CDK EKS Helm):
---

1. Doc this limitation explicitly and provide better tooling to assist users (either or combine below points or other way)
2. Allow an optional field to let user input values as a helm chart, but customer provide the helm chart location. User then can specify a helm chart with all custom values in one place, and rely on CDK to just pass in and use it. Then keep that helm chart with their SSP git repo code change for audit

Good thing:
There will be centralized way to keep the merging and avoid ambiguous merge
Full control the argocd helmchart without need CDK/SSP to constantly keep up with latest feature

Bad thing
There are now some configuration leaked out from CDK managed code into outside of CDK, which is not ideal

But did see some project with similar approaches to work around some customization around argocd, some may already need to do this way as there argocd is hosted internal git repo instead of public github repo, so they keep a copy along with SSP

3. [Not recommend] SSP itself will implement a brute force way:
An options to specify default helm chart values location, if so, try to download the pre-exist template and did merge in local SSP (which is like 2, but did merge automatic). Not recommend as above helm git topic points out, that merge of yaml may produce some unexpected problems, and not sure if really want to rely on that.

I think 1 and 2 probably is best we can do now (not sure 2 is okay by the team or it is totally outside of realm and only will suggest 1).

**Comment by shapirov103** [comment]
@allamand this has been fixed a few months ago. If you get a chance, do you mind confirming?

**Comment by shapirov103** [comment]
@danilko somehow I missed your original comment. The issue is more about how our add-on is structured. We allow passing values directly to the helm add-on as well as providing shortcuts to some of the values. When merging shortcuts with the passed values in some cases the values side was not retained and was overwritten. I believe it is resolved now, but looking for feedback.

**Comment by allamand** [comment]
Yes sorry forgot about the issue this is solved for me
