### ISSUE TITLE
(EMR AddOn): (Running e2e in two region fails at EMR Addon for a role)

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#553]
### Describe the bug

Running e2e in two region in same account fails at EMR Addon for a role by name as follows :
```
10:00:19 PM | CREATE_FAILED        | AWS::IAM::Role                        | myBlueprintExecRoleExecutionRole
myBlueprintExecRole already exists
```

### Expected Behavior

e2e should run fine in any region in same account

### Current Behavior

Fails with error :
```
10:00:19 PM | CREATE_FAILED        | AWS::IAM::Role                        | myBlueprintExecRoleExecutionRole
myBlueprintExecRole already exists
```

### Reproduction Steps

Run the blueprints-dev stack in two regions in same account

### CDK CLI Version

2.50.0

### EKS Blueprints Version

1.5.2

### Node.js Version

v19.0.1

### Environment details (OS name and version, etc.)

AL

**Comment by shapirov103** [comment]
@lmouhib do you mind taking a look? I believe this was brought up during the PR review.

**Comment by lmouhib** [comment]
This is an expected behavior. The IAM role need to be unique. If we want to deploy in two different regions then the user need to change the rolename. I submitted a PR to ensure uniqueness of the rolename. But I do not see a use case for EMR on EKS that requites the scenario you describe in the e2e test, it is on the user to ensure the uniqueness.

**Comment by lmouhib** [comment]
#555 solve this issue.

**Comment by shapirov103** [comment]
@elamaran11 do you mind rerunning the test case that failed and closing if it succeeds?

**Comment by elamaran11** [comment]
@shapirov103 Stack ran fine in secondary region. Closing the ticket.
