### ISSUE TITLE
New EKS CDK Blueprints Pattern for Graviton ARM64.

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#590]
### Describe the feature

A New EKS CDK Blueprints Pattern for Graviton ARM64 with a bunch of addons. A mechanism to reference and add addons to blueprints stack supporting ARM64.

### Use Case

Enable and create Graviton based EKS Clusters.

### Proposed Solution

A New EKS CDK Blueprints Pattern for Graviton ARM64 with a bunch of addons. A mechanism to reference and add addons to blueprints stack supporting ARM64.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.61.1

### EKS Blueprints Version

1.5.4

### Node.js Version

v19.4.0

### Environment details (OS name and version, etc.)

Mac M1

**Comment by Feder1co5oave** [comment]
I use Graviton instances in my Blueprint cluster by using Karpenter.
I specified 
```typescript
{
    'key': 'kubernetes.io/arch',
    'operator': 'In',
    'values': ['amd64', 'arm64']
}
```
in my default provisioner's `requirements`, and Graviton.
You can then put nodeSelector and nodeAffinity on pods, to decide on which arch to schedule them.
If your containers use multi-arch images, you can let it do its thing and automatically pull the right image for the selected node's arch.
If you don't specify the nodeSelector/affinity on arch, you risk running into CrashLoopBackOff issues, because images are pulled for the wrong arch, and you get executable format errors.

**Comment by Feder1co5oave** [comment]
I use Graviton instances in my Blueprint cluster by using Karpenter.
I specified 
```typescript
{
    'key': 'kubernetes.io/arch',
    'operator': 'In',
    'values': ['amd64', 'arm64']
}
```
in my default provisioner's `requirements`, and Graviton.
You can then put nodeSelector and nodeAffinity on pods, to decide on which arch to schedule them.
If your containers use multi-arch images, you can let it do its thing and automatically pull the right image for the selected node's arch.
If you don't specify the nodeSelector/affinity on arch, you risk running into CrashLoopBackOff issues, because images are pulled for the wrong arch, and you get executable format errors.

**Comment by Feder1co5oave** [comment]
I use Graviton instances in my Blueprint cluster by using Karpenter.
I specified 
```typescript
{
    'key': 'kubernetes.io/arch',
    'operator': 'In',
    'values': ['amd64', 'arm64']
}
```
in my default provisioner's `requirements`, and Graviton.
You can then put nodeSelector and nodeAffinity on pods, to decide on which arch to schedule them.
If your containers use multi-arch images, you can let it do its thing and automatically pull the right image for the selected node's arch.
If you don't specify the nodeSelector/affinity on arch, you risk running into CrashLoopBackOff issues, because images are pulled for the wrong arch, and you get executable format errors.

**Comment by elamaran11** [comment]
https://aws-samples.github.io/cdk-eks-blueprints-patterns/patterns/graviton/ Ready
