### ISSUE TITLE
Unable to add proxy configuration to EKS Blueprints Lambdas

### ISSUE THREAD

**Issue by mkorejo** [aws-quickstart/cdk-eks-blueprints#797]
### Describe the documentation issue

We need to add `http_proxy`, `https_proxy`, and `no_proxy` system environment variables to our Lambdas in order for them to properly get outbound to the internet and communicate with EKS control plane API. We have attempted to do this with [Aspects](https://docs.aws.amazon.com/cdk/v2/guide/aspects.html). Following is our code:

```
class Lambdaaspects implements cdk.IAspect {
  private environmentProps: any;
 
  constructor(environmentProps: any) {
    this.environmentProps = environmentProps;
  }

  public visit(node: IConstruct): void {
    // Check if we're dealing with a Function
    if (node instanceof CfnFunction) {
      // Set environment variable here
      this.addEnvironment(node);
   }
 }
 
private addEnvironment(node: CfnFunction): void {
    node.addOverride('Properties.Environment', this.environmentProps);
  }
}

const environmentProps = {
  Variables: {
    http_proxy : 'http://webproxyeva.fpl.com:8080',
    https_proxy: 'http://webproxyeva.fpl.com:8080',
    no_proxy: '*.fpl.com,*.neeaws.local,*.us-east-1.amazonaws.com,*.eks.amazonaws.com'
  },
};

// Apply the aspect to the stack
cdk.Aspects.of(app).add(new Lambdaaspects(environmentProps));
```

This does not have the desired effect of propagating the proxy environment variables to the EKS Blueprints Lambda functions.

What could we be missing or is there a better approach to adding these environment variables to the Blueprints Lambda functions.

### Links

https://docs.aws.amazon.com/cdk/v2/guide/aspects.html
https://stackoverflow.com/questions/60269108/how-to-automatically-put-environment-variable-to-all-lambdas-created-in-my-cdk-p

**Comment by shapirov103** [comment]
@mkorejo there are two requests in the issue: 1/ communication with the EKS control plane API and 2/ communication with the internet.

On the first request if you are talking about general EKS API communication, then you can use AWS Private Link  (since Dec 2022) to communicate with the EKS API (not control plane, but AWS CLI/API) privately. Here is [documentation](https://docs.aws.amazon.com/eks/latest/userguide/vpc-interface-endpoints.html) on this. 

If you need to communicate with the API endpoint, then you should be able to do so by placing the lambda functions in the target VPC of the cluster. 

For outbound access and injecting env variables to the custom resources produced by CDK, I believe CDK main repo would be a better choice for the issue: https://github.com/aws/aws-cdk/issues. Potentially related to https://github.com/aws/aws-cdk/issues/12171.
