### ISSUE TITLE
Selecting a specific EKS version with addons should select the "matching" AddOn versions automatically

### ISSUE THREAD

**Issue by Lock128** [aws-quickstart/cdk-eks-blueprints#812]
### Describe the feature

The EKS BluePrint (especially the fargate provider) should automatically select the related addon version for the Kubernetes version automatically.

see e.g. here
https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html

### Use Case

Essentially in this code:
https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/fargate-construct/index.ts

we would need to automatically select the version of the addons matchin to EKS Version 1.25 - otherwise the code will fail.

### Proposed Solution

see above

we could either read that online file (which exists for all addons) or get it from somewhere? e.g. CDK?

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

1.90.0

### EKS Blueprints Version

1.10.1

### Node.js Version

20.3.1

### Environment details (OS name and version, etc.)

macOS 13.5

**Comment by shapirov103** [comment]
@Lock128 it is a reasonable request, we have just addressed a similar one for kube-proxy and it is solved by maintaining the version mapping, e.g. the one [here](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/kube-proxy/index.ts#L4). 

The complexity of this solution is maintenance, because we don't have a clear channel to get notifications when versions are modified, upgraded or added. So unlike helm charts (not the oci, original ones based on index.yaml) there is no clear automatic check. 

However, I acknowledge that transferring this complexity to the customers is suboptimal. Let's see if others support this one as well, we can then roadmap it.

**Comment by Lock128** [comment]
Thanks for the feedback - its especially problematic as problems with this will only be visible during deployment time and there is no way to see the problems right now in the synth phase.
This then means 20+min wait time for another iteration if you got something wrong :-)

**Comment by Lock128** [comment]
So as there is no interest by anyone, does this mean that this issue will get closed again automtically?

**Comment by Lock128** [comment]
Removing stale :-)

**Comment by Lock128** [comment]
thanks for that @shapirov103, that a great step in the right direction. but isnt that a different thing - what if I want to be able to select it instead of using the default versions?

**Comment by elamaran11** [comment]
@Lock128 This is implemented in the above pointed PR. Please close the issue if you are good!

**Comment by Lock128** [comment]
Thank you both, I didnt understand that initially!
