### ISSUE TITLE
(addons/VpcCni): "Error: Region is missing"

### ISSUE THREAD

**Issue by JonVDB** [aws-quickstart/cdk-eks-blueprints#982]
### Describe the bug

When trying to `cdk synth` or `cd deploy` the sample cluster in the [Getting Started](https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/) guide, an error gets thrown. However, `synth` and `deploy` can still proceed to function.

Below is a copy of the error log stack when using `cdk synth` specifically and only with the VpcCni AddOn installed without arguments.
```
DEBUG Core add-on vpc-cni is at version auto
2024-04-10 12:32:04.818 WARN    \node_modules\@aws-quickstart\eks-blueprints\lib\addons\core-addon\index.ts:208 main
 Error  Region is missing
error stack:
  • \node_modules\@smithy\config-resolver\dist-cjs\index.js     default
        \node_modules\@smithy\config-resolver\dist-cjs\index.js:117
  • \node_modules\@smithy\node-config-provider\dist-cjs\index.js
        \node_modules\@smithy\node-config-provider\dist-cjs\index.js:72
  • \node_modules\@smithy\property-provider\dist-cjs\index.js
        \node_modules\@smithy\property-provider\dist-cjs\index.js:79
  • \node_modules\@smithy\property-provider\dist-cjs\index.js   async coalesceProvider
        \node_modules\@smithy\property-provider\dist-cjs\index.js:106
  • async \node_modules\@smithy\property-provider\dist-cjs\index.js
        async \node_modules\@smithy\property-provider\dist-cjs\index.js:117
  • \node_modules\@smithy\config-resolver\dist-cjs\index.js     async region
        \node_modules\@smithy\config-resolver\dist-cjs\index.js:142
  • \node_modules\@aws-sdk\client-eks\dist-cjs\auth\httpAuthSchemeProvider.js   async Object.defaultEKSHttpAuthSchemeParametersProvider [as httpAuthSchemeParametersProvider]
        \node_modules\@aws-sdk\client-eks\dist-cjs\auth\httpAuthSchemeProvider.js:9
  • async \node_modules\@smithy\core\dist-cjs\index.js
        async \node_modules\@smithy\core\dist-cjs\index.js:61
  • async \node_modules\@aws-sdk\middleware-logger\dist-cjs\index.js
        async \node_modules\@aws-sdk\middleware-logger\dist-cjs\index.js:33
  • \node_modules\@aws-quickstart\eks-blueprints\lib\addons\core-addon\index.ts async VpcCniAddOn.provideVersion
        \node_modules\@aws-quickstart\eks-blueprints\lib\addons\core-addon\index.ts:187
2024-04-10 12:32:04.821 WARN    \node_modules\@aws-quickstart\eks-blueprints\lib\addons\core-addon\index.ts:209 main    Failed to retrieve add-on versions from EKS for add-on vpc-cni. Falling back to default version.
DEBUG Core add-on vpc-cni has autoselected version v1.16.0-eksbuild.1
Description: Blueprints tracking (qs-1s1r465hk)
Resources:
[... truncated for brevity]]
```

The above error occurs when the below code is implemented in `bin/<mymainfile>.ts`
```
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import * as blueprints from '@aws-quickstart/eks-blueprints';


const app = new cdk.App();
const account = '<my-aws-account-id>';
const region = 'eu-west-1';
const version = 'auto';

const addOns: Array<blueprints.ClusterAddOn> = [
  new blueprints.addons.VpcCniAddOn(),
];

const stack = blueprints.EksBlueprint.builder()
  .account(account)
  .region(region)
  .version(version)
  .addOns(...addOns)
  .useDefaultSecretEncryption(false) // set to false to turn secret encryption off (non-production/demo cases)
  .build(app, 'eks-blueprint');
```

### Expected Behavior

No error logs in console when running `cdk synth/deploy`, especially because I already have the `region` configured.

### Current Behavior

"Region is missing" error logs in console, but `cdk synth` and `cdk deploy` still manage to run without further issues.

### Reproduction Steps

1. Start a new TypeScript project
2. Set `"profile": "profile-name"` in cdk.json
3. Configure `bin/<mymainfile>.ts` with the contents provided above
4. Run `cdk synth` in the console

### CDK CLI Version

2.133.0 (build dcc1e75)

### EKS Blueprints Version

1.14.1

### Node.js Version

v20.11.0

### Environment details (OS name and version, etc.)

Win11Pro22H2

**Comment by aluferraz** [comment]
As workaround,  you can set the AWS_REGION environment variable 

AWS_REGION=us-east-1 cdk deploy

**Comment by shapirov103** [comment]
Possible root cause: the issue affects core EKS addons (vpc-cni, kube-proxy, core-dns, etc.) which make a remote call to the EKS API at build time to determine the addon version for the target EKS version. 
The call is made using SDK (not CDK) and requires an active authentication profile, including region configuration. 

My understanding is that the synth command does not fail, you just get extra logs in the console. 

@elamaran11 let's review our logging strategy and make a doc to call out this behavior, so that in the future we can just point to a doc reference. I think we can improve the logging part, suppressing the error stack trace. I still we need to out the message, that version lookup failed, and possible reason (unauthorized, authn failed, network failure).

**Comment by elamaran11** [comment]
@shapirov103 SG, Will take a look on this.

**Comment by elamaran11** [comment]
@shapirov103 @JonVDB I tried to reproduce the error locally. I dont have the `AWS_REGION` parameter setup in my terminal and i tried to create a sample stack that was shared and i dont see the error you are facing. Also i see [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/350d562a5b64e08fa88e8539b5f133786b2d31ea/lib/addons/core-addon/index.ts#L180) code we wrote for last release, the `region` parameter is retrieved from `clusterInfo.cluster.stack.region` which is passed to the builder. So my hunch is, this is more of an interim issue that might have been caused by temporary unavailability of EKS API endpoints. 
@JonVDB Could you please try this again from your end and tell us if this issue is consistently occuring.

**Comment by aluferraz** [comment]
@shapirov103 @elamaran11  that's exactly the issue, here , for instance here:

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/350d562a5b64e08fa88e8539b5f133786b2d31ea/lib/addons/core-addon/index.ts#L180

The SDK call needs the region to be set, and since there is no way to set it from the cdk methods currently, my workaround was to set the default environment variable AWS_REGION :)

**Comment by elamaran11** [comment]
@aluferraz Do you get the above error when you dont `AWS_REGION` ?

**Comment by aluferraz** [comment]
> @aluferraz Do you get the above error when you dont `AWS_REGION` ?

yes

**Comment by elamaran11** [comment]
@aluferraz @JonVDB Im trying to recreate the issue with no luck. I created a new `cdk` project, added the same code to `bin` folder, unset `AWS_REGION` and finally added `profile` to `cdk.json` and i dont get this error with `cdk synth`. Are you folks using blueprints latest version `14.1` ?

**Comment by aluferraz** [comment]
Yes, the latest version.

You can check the value of  ```clusterInfo.cluster.stack.region```
In my case it was undefined, so the region must come from somewhere else, since region is required by ```"@smithy/types"```

**Comment by elamaran11** [comment]
Alright @aluferraz @JonVDB Im able to recreate the issue in a [DevContainer](https://github.com/aws-quickstart/cdk-eks-blueprints/pull/988) environment though i couldnt on my local terminal.

**Comment by elamaran11** [comment]
@shapirov103 [PR](https://github.com/aws-quickstart/cdk-eks-blueprints/pull/992) for this fix.

**Comment by aluferraz** [comment]
@shapirov103 @elamaran11 Thanks for the quick response! 
Setting the AWS_REGION works because the SDK fallback to environment variables in the absence of a region being informed on the parameters.

But, I believe that the root cause is  ```clusterInfo.cluster.stack.region``` being undefined here:

[cdk-eks-blueprints/lib/addons/core-addon/index.ts](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/350d562a5b64e08fa88e8539b5f133786b2d31ea/lib/addons/core-addon/index.ts#L180)

It should reflect the cluster region. We set the region here:

```
const stack = blueprints.EksBlueprint.builder()
  .account(account)
  .region(region)
```

So in order to use the SDK to get the addon version for the target EKS version, it should use the same region as we are deploying the cluster.


https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/eks/
